/******************************************************************************/
/*          Generated by IBExpert 2019.11.13.1 11/24/2019 6:47:17 PM          */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'C:\Documents\Projects\ControlePendencias\ControlePendencias\ControlePendencias.Data\Firebird\database.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_PENDENCIA_ID;
SET GENERATOR GEN_PENDENCIA_ID TO 10;

CREATE GENERATOR GEN_RESPONSAVEL_ID;
SET GENERATOR GEN_RESPONSAVEL_ID TO 9;



/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE SP_GEN_PENDENCIA_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SP_GEN_RESPONSAVEL_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^






SET TERM ; ^



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE PENDENCIA (
    ID              INTEGER NOT NULL,
    TITULO          VARCHAR(100) NOT NULL,
    DESCRICAO       VARCHAR(300) NOT NULL,
    DT_CADASTRO     TIMESTAMP NOT NULL,
    DT_FINAL        TIMESTAMP,
    STATUS          VARCHAR(30),
    PRIORIDADE      SMALLINT,
    COMPLEXIDADE    SMALLINT,
    ID_RESPONSAVEL  INTEGER NOT NULL
);


CREATE TABLE RESPONSAVEL (
    ID      INTEGER NOT NULL,
    NOME    VARCHAR(100) NOT NULL,
    EMAIL   VARCHAR(60) NOT NULL,
    FUNCAO  VARCHAR(30) NOT NULL
);




/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE PENDENCIA ADD CONSTRAINT PK_PENDENCIA PRIMARY KEY (ID);
ALTER TABLE RESPONSAVEL ADD CONSTRAINT PK_RESPONSAVEL PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE PENDENCIA ADD CONSTRAINT FK_PENDENCIA_RESP FOREIGN KEY (ID_RESPONSAVEL) REFERENCES RESPONSAVEL (ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: PENDENCIA_BI */
CREATE TRIGGER PENDENCIA_BI FOR PENDENCIA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_pendencia_id,1);
end
^


/* Trigger: RESPONSAVEL_BI */
CREATE TRIGGER RESPONSAVEL_BI FOR RESPONSAVEL
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_responsavel_id,1);
end
^

SET TERM ; ^



/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE SP_GEN_PENDENCIA_ID
RETURNS (
    ID INTEGER)
AS
begin
  id = gen_id(gen_pendencia_id, 1);
  suspend;
end^


ALTER PROCEDURE SP_GEN_RESPONSAVEL_ID
RETURNS (
    ID INTEGER)
AS
begin
  id = gen_id(gen_responsavel_id, 1);
  suspend;
end^



SET TERM ; ^

